# Site settings
title:       My Blog :)
description: "bakerz's blog"
baseurl:     /simplex

author: bakerz
email:  de1719@163.com
github: https://github.com/bakerz

#Build settings
markdown:    kramdown
highlighter: highlight.js