# Site settings
title:       My Blog :)
description: "zyuandong's blog"

author: 
  name: zyuandong
  email:  de1719@163.com
  github: https://github.com/zyuandong

# Serving
baseurl: ''

# Plugins
plugins:
  - jekyll-paginate

# Pagination
paginate: 10
paginate_path: "home/page:num"

# Outputting
permalink: posts/:title

# Markdown Processors
markdown: kramdown
kramdown:
    input: GFM

# Layout
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
