# Site settings
title:       My Blog :)
description: "zfareast's blog"

author: 
  name: zfareast
  email:  de1719@163.com
  github: https://github.com/zfareast

# Serving
baseurl: /simplex

# Outputting
permalink: /:year/:month/:day/:title

# Markdown Processors
markdown: kramdown
kramdown:
    input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "layout"