# Site settings
title:       My Blog :)
description: "bakerz's blog"

author: 
  name: bakerz
  email:  de1719@163.com
  github: https://github.com/bakerz

# Serving
baseurl: /simplex

# Outputting
permalink: /:year/:month/:day/:title

# Markdown Processors
markdown: kramdown
kramdown:
    input: GFM

defaults:
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"